version: '2'
services:
    idleflix-app:
        image: idleflix
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://idleflix-mysql:3306/idleflix?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    idleflix-mysql:
        extends:
            file: mysql.yml
            service: idleflix-mysql
